import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import { MarkdownText } from "./MarkdownText";
import type { AssessmentPackRead } from "@/types/api";

const s = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica", color: "#1a1a1a" },
  title: { fontSize: 20, fontWeight: "bold", marginBottom: 4 },
  subtitle: { fontSize: 11, color: "#666", marginBottom: 16 },
  metaRow: { flexDirection: "row", gap: 16, marginBottom: 20, fontSize: 10, color: "#555" },
  sectionTitle: { fontSize: 14, fontWeight: "bold", marginBottom: 10, color: "#333" },
  questionBlock: { marginBottom: 14, paddingBottom: 10, borderBottomWidth: 0.5, borderBottomColor: "#e5e5e5" },
  qHeader: { flexDirection: "row", marginBottom: 4 },
  qNumber: { width: 28, fontWeight: "bold", color: "#7c3aed" },
  qTextWrap: { flex: 1 },
  qText: { lineHeight: 1.5 },
  qMeta: { fontSize: 9, color: "#888", marginTop: 2, marginLeft: 28 },
  optionRow: { flexDirection: "row", marginLeft: 28, marginTop: 3 },
  optionLabel: { width: 18, fontWeight: "bold", color: "#888", fontSize: 10 },
  optionText: { flex: 1, fontSize: 10 },
  lines: { marginLeft: 28, marginTop: 6 },
  line: { borderBottomWidth: 0.5, borderBottomColor: "#ccc", height: 20 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 8, color: "#aaa", textAlign: "center" },
});

interface AssessmentPDFProps {
  pack: AssessmentPackRead;
}

export const AssessmentPDF = ({ pack }: AssessmentPDFProps) => {
  const lineCount = (type: string) => {
    if (type.toLowerCase().includes("long") || type.toLowerCase().includes("essay")) return 8;
    if (type.toLowerCase().includes("short")) return 3;
    if (type.toLowerCase().includes("problem")) return 5;
    return 0;
  };

  return (
    <Document>
      <Page size="A4" style={s.page}>
        <Text style={s.title}>{pack.title ?? "Assessment"}</Text>
        <Text style={s.subtitle}>
          {[pack.subject, pack.grade_level && `Grade ${pack.grade_level}`, pack.assessment_type]
            .filter(Boolean)
            .join(" · ")}
        </Text>

        <View style={s.metaRow}>
          {pack.total_marks != null && <Text>Total marks: {pack.total_marks}</Text>}
          {pack.estimated_time_minutes != null && <Text>Time: {pack.estimated_time_minutes} min</Text>}
        </View>

        <Text style={s.sectionTitle}>Questions</Text>

        {pack.questions?.map((q) => (
          <View key={q.question_number} style={s.questionBlock} wrap={false}>
            <View style={s.qHeader}>
              <Text style={s.qNumber}>{q.question_number}.</Text>
              <View style={s.qTextWrap}>
                <MarkdownText style={s.qText}>{q.question_text}</MarkdownText>
              </View>
            </View>
            <Text style={s.qMeta}>
              [{q.marks} mark{q.marks !== 1 ? "s" : ""}] · {q.question_type}
            </Text>

            {/* MCQ options */}
            {q.options &&
              q.options.map((opt, i) => (
                <View key={i} style={s.optionRow}>
                  <Text style={s.optionLabel}>{String.fromCharCode(65 + i)}.</Text>
                  <Text style={s.optionText}>{opt}</Text>
                </View>
              ))}

            {/* Answer lines for non-MCQ */}
            {(!q.options || q.options.length === 0) && lineCount(q.question_type) > 0 && (
              <View style={s.lines}>
                {Array.from({ length: lineCount(q.question_type) }).map((_, i) => (
                  <View key={i} style={s.line} />
                ))}
              </View>
            )}
          </View>
        ))}

        <Text style={s.footer}>
          Generated by AIME Lesson Studio · {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
};
