import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import { MarkdownText } from "./MarkdownText";
import type { HomeworkRead } from "@/types/api";

const s = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica", color: "#1a1a1a" },
  title: { fontSize: 20, fontWeight: "bold", marginBottom: 4 },
  subtitle: { fontSize: 11, color: "#666", marginBottom: 16 },
  metaRow: { flexDirection: "row", gap: 16, marginBottom: 20, fontSize: 10, color: "#555" },
  sectionTitle: { fontSize: 13, fontWeight: "bold", marginBottom: 8, color: "#333" },
  instruction: { fontSize: 10, color: "#444", marginBottom: 3, marginLeft: 12 },
  bullet: { fontSize: 10, color: "#888", marginRight: 6 },
  instructionRow: { flexDirection: "row", marginBottom: 3 },
  taskBlock: { marginBottom: 12, paddingBottom: 8, borderBottomWidth: 0.5, borderBottomColor: "#e5e5e5" },
  taskHeader: { flexDirection: "row", marginBottom: 4 },
  taskNumber: { width: 28, fontWeight: "bold", color: "#7c3aed" },
  taskTextWrap: { flex: 1 },
  taskText: { lineHeight: 1.5 },
  taskMeta: { fontSize: 9, color: "#888", marginTop: 2, marginLeft: 28 },
  submissionNote: { fontSize: 10, fontStyle: "italic", color: "#666", marginTop: 16, padding: 8, backgroundColor: "#f8f8f8", borderRadius: 3 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 8, color: "#aaa", textAlign: "center" },
});

interface HomeworkPDFProps {
  homework: HomeworkRead;
  lessonTitle?: string;
}

export const HomeworkPDF = ({ homework, lessonTitle }: HomeworkPDFProps) => (
  <Document>
    <Page size="A4" style={s.page}>
      <Text style={s.title}>{homework.title ?? "Homework"}</Text>
      {lessonTitle && <Text style={s.subtitle}>{lessonTitle}</Text>}

      <View style={s.metaRow}>
        {homework.total_marks > 0 && <Text>Total marks: {homework.total_marks}</Text>}
      </View>

      {/* Instructions */}
      {homework.student_instructions && homework.student_instructions.length > 0 && (
        <View style={{ marginBottom: 16 }}>
          <Text style={s.sectionTitle}>Instructions</Text>
          {homework.student_instructions.map((inst, i) => (
            <View key={i} style={s.instructionRow}>
              <Text style={s.bullet}>•</Text>
              <MarkdownText style={s.instruction}>{inst}</MarkdownText>
            </View>
          ))}
        </View>
      )}

      {/* Tasks */}
      {homework.tasks && homework.tasks.length > 0 && (
        <View>
          <Text style={s.sectionTitle}>Tasks</Text>
          {homework.tasks.map((task) => (
            <View key={task.task_number} style={s.taskBlock} wrap={false}>
              <View style={s.taskHeader}>
                <Text style={s.taskNumber}>{task.task_number}.</Text>
                <View style={s.taskTextWrap}>
                  <MarkdownText style={s.taskText}>{task.task_text}</MarkdownText>
                </View>
              </View>
              <Text style={s.taskMeta}>
                [{task.marks} mark{task.marks !== 1 ? "s" : ""}]
              </Text>
            </View>
          ))}
        </View>
      )}

      {/* Submission note */}
      {homework.submission_note && (
        <Text style={s.submissionNote}>{homework.submission_note}</Text>
      )}

      <Text style={s.footer}>
        Generated by AIME Lesson Studio · {new Date().toLocaleDateString()}
      </Text>
    </Page>
  </Document>
);
