import { marked } from "marked";
import type { AssessmentPackRead } from "@/types/api";

const css = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    font-size: 12pt;
    color: #1a1a1a;
    line-height: 1.6;
    padding: 40px;
  }
  h1 { font-size: 22pt; font-weight: 700; margin-bottom: 4px; }
  .subtitle { font-size: 11pt; color: #666; margin-bottom: 12px; }
  .meta { display: flex; gap: 24px; font-size: 10pt; color: #555; margin-bottom: 24px; padding-bottom: 12px; border-bottom: 1px solid #e5e5e5; }
  .section-title { font-size: 14pt; font-weight: 700; color: #333; margin-bottom: 16px; }
  .question { margin-bottom: 20px; padding-bottom: 16px; border-bottom: 1px solid #f0f0f0; page-break-inside: avoid; }
  .question:last-child { border-bottom: none; }
  .q-header { display: flex; gap: 10px; margin-bottom: 6px; }
  .q-number { font-weight: 700; color: #7c3aed; min-width: 28px; }
  .q-text { flex: 1; }
  .q-text p { margin-bottom: 4px; }
  .q-text ul, .q-text ol { margin-left: 20px; margin-bottom: 4px; }
  .q-marks { font-size: 9pt; color: #888; margin-left: 38px; margin-bottom: 8px; }
  .options { margin-left: 38px; }
  .option { display: flex; gap: 8px; padding: 4px 0; font-size: 11pt; }
  .option-label { font-weight: 600; color: #888; min-width: 20px; }
  .option-text p { margin: 0; display: inline; }
  .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e5e5; font-size: 8pt; color: #aaa; text-align: center; }
  code { font-family: 'Consolas', 'Courier New', monospace; background: #f5f5f5; padding: 1px 4px; border-radius: 3px; font-size: 0.9em; }
  pre { background: #f5f5f5; padding: 8px 12px; border-radius: 4px; margin: 8px 0; overflow-x: auto; }
  pre code { background: none; padding: 0; }
  @media print {
    body { padding: 0; }
    .question { page-break-inside: avoid; }
  }
`;

export function generateAssessmentHtml(pack: AssessmentPackRead): string {
  const subtitleParts = [
    pack.subject,
    pack.grade_level && `Grade ${pack.grade_level}`,
  ].filter(Boolean);

  const metaParts: string[] = [];
  if (pack.total_marks != null)
    metaParts.push(`Total: ${pack.total_marks} marks`);
  if (pack.estimated_time_minutes != null)
    metaParts.push(`Time: ${pack.estimated_time_minutes} min`);

  const questionsHtml = (pack.questions ?? [])
    .map((q) => {
      const textHtml = marked.parse(q.question_text, {
        async: false,
      }) as string;

      let optionsHtml = "";
      if (q.options && q.options.length > 0) {
        const optItems = q.options
          .map((opt, i) => {
            const optText = marked.parse(opt, { async: false }) as string;
            return `<div class="option"><span class="option-label">${String.fromCharCode(65 + i)}.</span><span class="option-text">${optText}</span></div>`;
          })
          .join("");
        optionsHtml = `<div class="options">${optItems}</div>`;
      }

      return `
        <div class="question">
          <div class="q-header">
            <span class="q-number">${q.question_number}.</span>
            <div class="q-text">${textHtml}</div>
          </div>
          <div class="q-marks">[${q.marks} mark${q.marks !== 1 ? "s" : ""}]</div>
          ${optionsHtml}
        </div>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><style>${css}</style></head>
<body>
  <h1>${pack.title ?? "Assessment"}</h1>
  ${subtitleParts.length > 0 ? `<div class="subtitle">${subtitleParts.join(" · ")}</div>` : ""}
  ${metaParts.length > 0 ? `<div class="meta">${metaParts.map((m) => `<span>${m}</span>`).join("")}</div>` : ""}
  <div class="section-title">Questions</div>
  ${questionsHtml}
  <div class="footer">Generated by AIME Lesson Studio · ${new Date().toLocaleDateString()}</div>
</body>
</html>`;
}
