import { marked } from "marked";
import type { HomeworkRead } from "@/types/api";

const css = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    font-size: 12pt;
    color: #1a1a1a;
    line-height: 1.6;
    padding: 40px;
  }
  h1 { font-size: 22pt; font-weight: 700; margin-bottom: 4px; }
  .subtitle { font-size: 11pt; color: #666; margin-bottom: 12px; }
  .meta { font-size: 10pt; color: #555; margin-bottom: 24px; padding-bottom: 12px; border-bottom: 1px solid #e5e5e5; }
  .section-title { font-size: 14pt; font-weight: 700; color: #333; margin-bottom: 10px; }
  .instructions { margin-bottom: 24px; }
  .instructions ul { margin-left: 20px; list-style: disc; }
  .instructions li { font-size: 11pt; color: #444; margin-bottom: 4px; }
  .task { margin-bottom: 16px; padding-bottom: 12px; border-bottom: 1px solid #f0f0f0; page-break-inside: avoid; }
  .task:last-child { border-bottom: none; }
  .task-header { display: flex; gap: 10px; margin-bottom: 4px; }
  .task-number { font-weight: 700; color: #7c3aed; min-width: 28px; }
  .task-text { flex: 1; }
  .task-text p { margin-bottom: 4px; }
  .task-text ul, .task-text ol { margin-left: 20px; margin-bottom: 4px; }
  .task-marks { font-size: 9pt; color: #888; margin-left: 38px; }
  .submission-note { margin-top: 24px; padding: 12px; background: #f8f8f8; border-radius: 4px; font-size: 10pt; color: #666; font-style: italic; }
  .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e5e5; font-size: 8pt; color: #aaa; text-align: center; }
  code { font-family: 'Consolas', 'Courier New', monospace; background: #f5f5f5; padding: 1px 4px; border-radius: 3px; font-size: 0.9em; }
  pre { background: #f5f5f5; padding: 8px 12px; border-radius: 4px; margin: 8px 0; overflow-x: auto; }
  pre code { background: none; padding: 0; }
  @media print {
    body { padding: 0; }
    .task { page-break-inside: avoid; }
  }
`;

export function generateHomeworkHtml(
  homework: HomeworkRead,
  lessonTitle?: string,
): string {
  let instructionsHtml = "";
  if (
    homework.student_instructions &&
    homework.student_instructions.length > 0
  ) {
    const items = homework.student_instructions
      .map((inst) => {
        const html = marked.parse(inst, { async: false }) as string;
        return `<li>${html}</li>`;
      })
      .join("");
    instructionsHtml = `
      <div class="instructions">
        <div class="section-title">Instructions</div>
        <ul>${items}</ul>
      </div>`;
  }

  const tasksHtml = (homework.tasks ?? [])
    .map((task) => {
      const textHtml = marked.parse(task.task_text, { async: false }) as string;
      return `
        <div class="task">
          <div class="task-header">
            <span class="task-number">${task.task_number}.</span>
            <div class="task-text">${textHtml}</div>
          </div>
          <div class="task-marks">[${task.marks} mark${task.marks !== 1 ? "s" : ""}]</div>
        </div>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><style>${css}</style></head>
<body>
  <h1>${homework.title ?? "Homework"}</h1>
  ${lessonTitle ? `<div class="subtitle">${lessonTitle}</div>` : ""}
  ${homework.total_marks > 0 ? `<div class="meta">Total: ${homework.total_marks} marks</div>` : ""}
  ${instructionsHtml}
  ${tasksHtml.length > 0 ? `<div class="section-title">Tasks</div>${tasksHtml}` : ""}
  ${homework.submission_note ? `<div class="submission-note">${homework.submission_note}</div>` : ""}
  <div class="footer">Generated by AIME Lesson Studio · ${new Date().toLocaleDateString()}</div>
</body>
</html>`;
}
